postgres:
  addr: "${DB_ADDR:-localhost:5432}"
  db: "${DB:-demo}"

  # пользователь для чтения репликации
  replication_user: "${TKCDC_REPLICATION_USER:-tkcdc_replication_user}"
  replication_pass: "${TKCDC_REPLICATION_PASS:-tkcdc_replication_pass}"

  # отдельный полльзователь для выполнения операций проверки наличия слота и получения LSN
  app_user: "${TKCDC_USER:-tkcdc_user}"
  app_pass: "${TKCDC_PASS:-tkcdc_pass}"

  # имя слота логической репликации
  # если слот не существует - сервис попытается создать его при старте
  replication_slot: "${PG_SLOT:-redis_invalidator}"

  # плагин декодирования сообщений WAL, важно для формата сообщений
  plugin: "pgoutput"

  # имя публикаций, которые отслеживаем через запятую
  publication_names: "${PUBLICATION_NAMES:-test_pub}"

redis:
  addr: "{REDIS_ADDR:-localhost:6379}"
  password: "${REDIS_PASSWORD:-}"

  # номер логической базы данных в Redis
  db: 0

  # кол-во повторных попыток выполнения запросов redis
  query_max_attempts: 3
  query_delay_ms: 10

mapping:
  default_schema: "public"
  rules:
    - table: "users" # имя таблицы postgres, чьи поля нужно отслеживать
      # таблица должна иметь PK или иметь UNIQUE NOT NULL поле с настроенным REPLICA IDENTITY USING INDEX
      # для однозначной идентификации записи

      # шаблон ключа в redis, который будет удаляться при изменении строки в postgres
      # в фигурных скобках указано имя поля в postgres (обычно PK), значение которого будет подставляться
      # ! ключи в redis плоские, удаление "user:123" НЕ удалит "user:123:email"
      key_pattern: "user:{id}"
